version: "2"
linters:
  default: all
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - golang.org/x/crypto/*
    errcheck:
      check-type-assertions: true
      check-blank: true
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bytemare/hash)
        - blank
        - dot
        - alias
    gocritic:
      enable-all: true
    goimports:
      local-prefixes: github.com/bytemare/hash
    gosec:
      excludes:
        - G115
    govet:
      shadow: true
      enable-all: true
    interfacebloat:
      max: 11
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - 256
        - 512
        - 1600
    prealloc:
      simple: false
      for-loops: true
  exclusions:
    rules:
      - path: extensible.go
        linters:
          - errcheck
          - exhaustive
          - gci
          - gofumpt
          - goimports
      - path: fixed.go
        linters:
          - errcheck
          - exhaustive
          - gci
          - gofumpt
          - goimports
      - path: hash.go
        linters:
          - gochecknoglobals
          - gochecknoinits
          - ireturn
          - revive
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bytemare/hash)
        - blank
        - dot
        - alias
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/bytemare/hash
    golines:
      max-len: 200
output:
  sort-order:
    - file
run:
  tests: false