name: Bug Report
description: Report a reproducible problem with github.com/bytemare/hash.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for helping improve the project! Provide as much detail as possible so we can reproduce the issue.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug.
      placeholder: HashToGroup panics when DST is empty
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Go version, OS/architecture, ecc version or commit.
      placeholder: |
        - Go: 1.25.1
        - ecc: v0.10.0
        - OS: linux/amd64
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide code snippets, commands, or links to failing tests.
      placeholder: |
        1. Call group.HashToGroup(nil, dst)
        2. Observe panic message
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened? Include stack traces or logs if available.
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions.
          required: true
        - label: I read the [security policy](../SECURITY.md) and this is **not** a vulnerability report.
          required: true
