name: Feature Request
description: Suggest an enhancement for github.com/bytemare/hash.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for sharing ideas! Fill in as much context as you can so we can evaluate the request.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short title for the feature.
      placeholder: Support new hash function X
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this feature solve? Who benefits from it?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline API changes, new behaviour, or references to relevant specifications.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you evaluated and why they were rejected.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links to related issues, benchmarks, or external requirements.
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions for similar requests.
          required: true
        - label: This request aligns with the [Code of Conduct](../../CODE_OF_CONDUCT.md).
          required: true
