name: Hash
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017 # pin@master
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@be1aa1186e83689f3e45adaf3697af86f816fb2e # pin@master
        with:
          go-version-file: ./go.mod

      # Linting
      - name: Linting
        uses: golangci/golangci-lint-action@66db41e5ddf31df5a4b82871778d9efc99624520 # pin@master
        with:
          version: latest
          args: --config=./.github/.golangci.yml ./...
          only-new-issues: true

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22' ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017 # pin@master
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@be1aa1186e83689f3e45adaf3697af86f816fb2e # pin@master
        with:
          go-version: ${{ matrix.go }}

      # Test
      - name: Run Tests
        run: cd .github && make test

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017 # pin@master
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@be1aa1186e83689f3e45adaf3697af86f816fb2e # pin@master
        with:
          go-version-file: ./go.mod

      # Coverage
      - name: Run coverage
        run: cd .github && make cover

      # Codecov
      - name: Codecov
        uses: codecov/codecov-action@164fadeaa7c9c2f7ff8ed535672bfab80abdf570 # pin@master
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: .github/coverage.out

      # Sonar
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@76ec6e7459bd65c7a7ade7d4c7b68d6f0df353c8 # pin@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=bytemare_hash
            -Dsonar.organization=bytemare-github
            -Dsonar.go.coverage.reportPaths=.github/coverage.out
            -Dsonar.sources=.
            -Dsonar.test.exclusions=tests/**
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
