name: Code Scan

on:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    uses: bytemare/actions/.github/workflows/golangci-lint.yml@5e46fe7caed6926b5ce48bf5c5d12a79aa074fd3
    with:
      config-path: ./.github/.golangci.yml
      scope: ./...

  Analyze:
    uses: bytemare/actions/.github/workflows/scan-go.yml@5e46fe7caed6926b5ce48bf5c5d12a79aa074fd3
    with:
      sonar-organization: bytemare-github
      sonar-project-key: bytemare_hash
      sonar-tests: tests/
      sonar-test-exclusions: examples_test.go,tests/**
      sonar-coverage-exclusions: examples_test.go,tests/**
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}
      codecov: ${{ secrets.CODECOV_TOKEN }}
