name: Code Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '4 1 * * *'

jobs:
  Lint:
    uses: bytemare/actions/.github/workflows/golangci-lint.yml@9187f5166667ef0ce72184900f08e39540b348c3
    with:
      config-path: ./.github/.golangci.yml
      scope: ./...

  Analyze:
    uses: bytemare/actions/.github/workflows/scan-go.yml@9187f5166667ef0ce72184900f08e39540b348c3
    with:
      sonar-configuration: .github/sonar-project.properties
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}
      codecov: ${{ secrets.CODECOV_TOKEN }}
      semgrep: ${{ secrets.SEMGREP_APP_TOKEN }}