name: Do Stuff

on:
  pull_request:
    branches:
      - main

jobs:

  Lint:
    uses: bytemare/actions/.github/workflows/golang-ci.yml@main
    with:
      config-path: ./.github/.golangci.yml
      scope: ./...

  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/actions/.github/workflows/test-go.yml@main
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}

  Analyze:
    uses: bytemare/actions/.github/workflows/scan-go.yml@main
    with:
      organization: bytemare-github
      project-key: bytemare_hash
      sources: .
      exclusions: ""
      tests: tests/
      test-exclusions: examples_test.go,tests/**
      coverage-exclusions: examples_test.go,tests/**
      verbose: true
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}
      codecov: ${{ secrets.CODECOV_TOKEN }}