name: Scorecard Analysis Workflow
on:
  # Only the default branch is supported. By default all modifications trigger the workflow.
  branch_protection_rule:
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  push:
    branches: [ main ]

# Declare default permissions as read-only.
permissions: read-all

jobs:
  Analysis:
    uses: bytemare/actions/.github/workflows/scorecard.yml@ac373b63aa8863380de843ddebfd42baabf57703
    secrets:
      token: ${{ secrets.SCORECARD_TOKEN }}
