name: Snyk

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '31 10 * * 0'

permissions:
  contents: read

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Snyk
        uses: snyk/actions@0.3.0
