name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@f597e6a31cf20179c6545b10e4bf433b51a891a9
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
