name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@12c66a077ea4bf80f077cc12348147b066386bb3
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
