name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@5193edc9697012dff47597f9e360f3054972aa39
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
