name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Declare default permissions as read-only.
permissions: read-all

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/actions/.github/workflows/test-go.yml@ac373b63aa8863380de843ddebfd42baabf57703
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
