name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/actions/.github/workflows/test-go.yml@5e46fe7caed6926b5ce48bf5c5d12a79aa074fd3
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
