name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/actions/.github/workflows/test-go.yml@fbcba37214781155710d371293998c2a129853b2
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
