name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/actions/.github/workflows/test-go.yml@1e5a173454a4f4c4686fc9b07a2a34db9c0e963e
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
