name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@1373d41b5cd4c4775029362712dc2e661add0cc2
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
